создал каркас для нового api, добавил модели и процессоры для внешних команд, удалил ненужные api(в соответсвие с swagger )
yoursweet667/UNO_Backend pull request #11
Opened 2021-05-21 15:06 UTC by yoursweet667

2021-05-25 07:52 UTC, phreakiboi requested changes

2021-05-25 07:52 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/web/controller/CommandController.java
> +                             @RequestParam CommandType commandType, @RequestParam Card card) {
`@RequestParam String playerId, @RequestParam CommandType commandType, @RequestParam Card card` это не соответствует твоему api

2021-05-25 07:52 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/web/controller/EventController.java
> +=======
тут у тебя merge conflict, почитай как фиксить это для git

2021-05-31 15:58 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/web/controller/EventController.java
> +=======
исправил

2021-06-01 11:25 UTC, phreakiboi approved these changes

2021-06-01 11:25 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/command/model/PlayCardCommand.java
> +public class PlayCardCommand {
добавь в новые классы команд hashCode и equals метода

2021-06-04 15:22 UTC, merged