Create cards in game service
yoursweet667/UNO_Backend pull request #2
Opened 2021-02-04 15:54 UTC by yoursweet667

fix card types, colors, create them in the game

2021-02-04 16:08 UTC, phreakiboi requested changes

2021-02-04 16:08 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +            for (int i = 1; i <= numberOfCards; i++) {
You repeat this for loop inside of every if/else. Instead, you can have just one for loop and put all if/elses inside.

2021-02-04 16:08 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +                Card cardPlus4 = new Card(cardType, CardColour.BLACK);
I don't think we need BLACK color, since it's not going to be used anywhere - card type is just enough for all the logic.

2021-02-04 16:08 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +        for (int i = 1; i <= numberOfCards; i++) {
this code will be executed even if card type is CHANGE_COLOUR or PLUS_4

2021-02-04 16:08 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +    public List<Card> createCards(int numberOfCards, CardType cardType) {
I think this method can be even moved out to a separate class. This would allow to make it testable independently from the rest of this class' logic.

2021-02-08 15:39 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +            for (int i = 1; i <= numberOfCards; i++) {
done

2021-02-08 15:40 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +    public List<Card> createCards(int numberOfCards, CardType cardType) {
i have made a new class

2021-02-08 15:40 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +        for (int i = 1; i <= numberOfCards; i++) {
fixed

2021-02-08 15:41 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +                Card cardPlus4 = new Card(cardType, CardColour.BLACK);
deleted BLACK color, cause it's useless

2021-02-08 15:46 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/validator/TakeCardsValidator.java
> +            for (CardType cardTypeInGame : CardType.values()) {
why do you need to iterate over all card types? I think that only lastCardInTheGame.getType() matters.

2021-02-08 15:51 UTC, phreakiboi requested changes

2021-02-08 15:51 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/CardFactory.java
> +            int numberOfCard;
numberOfCards is a correct name

2021-02-08 15:51 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +    public void getCards(String gameId) {
What is this method used for?

2021-02-15 12:20 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/validator/TakeCardsValidator.java
> +            for (CardType cardTypeInGame : CardType.values()) {
fixed

2021-02-15 12:20 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/CardFactory.java
> +            int numberOfCard;
renamed

2021-02-15 12:21 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +    public void getCards(String gameId) {
forgot delete this, now it's done

2021-02-17 09:26 UTC, phreakiboi requested changes

2021-02-17 13:22 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/validator/PlayCardValidator.java
> +                .orElseThrow(() -> new IllegalArgumentException("Next Player Isn't Found"))
because exception depends on argument

2021-02-17 13:27 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/CardFactory.java
> +            int howMuchTimesCrateCard;
i think _howMuchTimesCrateCard_ better, more clear

2021-02-17 13:29 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/validator/LeaveGameValidatorTest.java
> +    void validator_playerAlreadyRemoved_ThrowsException() {
agree with you

2021-02-17 13:30 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/validator/TakeCardsValidatorTest.java
> +    void validate_playerCardsIsNotZero_exception() {
yeah, fixed

2021-02-17 13:41 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/validator/TakeCardsValidatorTest.java
> +    TakeCardsValidator takeCardsValidator = new TakeCardsValidator();
done

2021-02-22 08:21 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/validator/TakeCardsValidatorTest.java
> +    void validate_eventHasMoreThanSevenCards_exception() {
I've learned it and fixed

2021-02-22 08:21 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/validator/JoinGameValidatorTest.java
> +        //Then
fixed

2021-02-22 13:14 UTC, merged