create unit tests for processors and services
yoursweet667/UNO_Backend pull request #5
Opened 2021-03-07 07:45 UTC by yoursweet667

2021-03-07 08:58 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/LeaveGameProcessorTest.java
> +    LeaveGameProcessor leaveGameProcessor = new LeaveGameProcessor();
can be private final. Same comment for other tests.

2021-03-07 08:58 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/LeaveGameProcessorTest.java
> +        assertThat(game.getPlayers()).doesNotContainValue(player);
Instead, check that players map doesn't contain the playerId key. If there's no key - there's no value.

2021-03-07 08:58 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/PlayCardProcessorTest.java
> +        assertThat(game.getCardsInTheGame()).contains(card);
check that this is the last card in the game

2021-03-07 08:58 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/SkipTurnProcessorTest.java
> +    void doProcess_setRightNextPlayer() {
'Correct' word suits here better than 'Right'

2021-03-07 08:58 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/TakeCardsProcessorTest.java
> +    void doProcess_anyGameState_takeCards() {
any game state?

2021-03-07 08:58 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(game).isNotNull();
Check that games properties are initialized correctly. Check that there are cards, etc.

2021-03-08 07:40 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/LeaveGameProcessorTest.java
> +    LeaveGameProcessor leaveGameProcessor = new LeaveGameProcessor();
done

2021-03-08 07:42 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/LeaveGameProcessorTest.java
> +        assertThat(game.getPlayers()).doesNotContainValue(player);
changes has been made

2021-03-08 07:52 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/PlayCardProcessorTest.java
> +        assertThat(game.getCardsInTheGame()).contains(card);
made a check

2021-03-08 07:53 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/SkipTurnProcessorTest.java
> +    void doProcess_setRightNextPlayer() {
changed

2021-03-08 08:02 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/TakeCardsProcessorTest.java
> +    void doProcess_anyGameState_takeCards() {
any allowed

2021-03-08 08:50 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(game).isNotNull();
Done

2021-03-20 08:57 UTC, phreakiboi requested changes

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +        Mockito.when(inMemoryGameStorage.getGame(GAME_ID)).thenReturn(Optional.of(game));
You're supposed to test `inMemoryGameStorage.getGame(GAME_ID)` here. But you're mocking its behavior, which means you're not testing `getGame`, but you're testing a mock.

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/EventServiceImplTest.java
> +    void getEvents_gameExistChangeEventParams_getNeededEvents() {
This name is confusing. How about `getEvents_eventsContainOthePlayersSensitiveData_returnedEventsHaveHiddenDetails`

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndGameProcessorTest.java
> +    void doProcess_anyGameState_changeGameState() {
Does `_anyGameState_` actually matter for this test? If not - just remove this.

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndTurnProcessorTest.java
> +    private static class ValueHoldingBiConsumer implements BiConsumer<String, Event> {
Would be better to remove `ValueHoldingBiConsumer` from tests and use mock + mockito.verify instead, just like you've done for one of the test classes.

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/PlayCardProcessorTest.java
> +    void doProcess_addCardInGameAndDeleteInPlayer() {
_addCardToGameAndRemoveItFromPlayer

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/TakeCardsProcessorTest.java
> +    void doProcess_anyAllowedGameState_takeCards() {
You say `_anyAllowedGameState_`, but in the tests code I see `GameState.START_TURN`

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(game.getGameState()).isNotNull();
Should it be ANY not null state or a particular one?

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(game.getDeck()).isNotEmpty();
Check that at least it has a correct number of cards. This test right now will pass even if `createGame()` will create a deck of just 1 card.

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +    void addPlayerToGame_addPlayerToLocalGame() {
I don't understand what `Local` means here.

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +    void addPlayerToGame_gameNotFound_exception() {
I don't see anything related to exception in this test's code.

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        Player player = gameServiceImpl.addPlayerToGame(GAME_ID, "playerName");
why are you calling `addPlayerToGame` in `removePlayerFromGame_removePlayer` test?

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +    void removePlayerFromGame_gameNotFound_exception() {
don't see exceptions in the code of this test

2021-03-20 08:57 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(gameFromStorage.get().getGameId()).isEqualTo(game.getGameId());
Don't check that IDs are equal, check that games are equal

2021-03-21 08:40 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(gameFromStorage.get().getGameId()).isEqualTo(game.getGameId());
Fixed it

2021-03-21 11:22 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndGameProcessorTest.java
> +    void doProcess_anyGameState_changeGameState() {
ok

2021-03-21 11:33 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/PlayCardProcessorTest.java
> +    void doProcess_addCardInGameAndDeleteInPlayer() {
Changed that

2021-03-21 11:56 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +    void addPlayerToGame_addPlayerToLocalGame() {
actually nothing, deleted it

2021-03-21 14:00 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/EventServiceImplTest.java
> +    void getEvents_gameExistChangeEventParams_getNeededEvents() {
renamed it

2021-03-22 15:51 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +    void removePlayerFromGame_gameNotFound_exception() {
this test was written incorrectly, now it is fixed

2021-03-22 16:14 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(game.getGameState()).isNotNull();
it must be GAME_CREATED

2021-03-22 16:16 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(game.getDeck()).isNotEmpty();
fixed it

2021-03-22 18:32 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +        Mockito.when(inMemoryGameStorage.getGame(GAME_ID)).thenReturn(Optional.of(game));
Fixed it

2021-03-22 18:42 UTC, closed without merging