#4 build event logic
yoursweet667/UNO_Backend pull request #6
Opened 2021-03-19 17:45 UTC by yoursweet667

2021-03-27 20:45 UTC, phreakiboi requested changes

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/EventServiceImpl.java
> +    private Card changeCardsParams(Card card) {
rename to hideCardsDetails

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/EventServiceImpl.java
> +        Card changedCard = new Card(card.getType(), card.getColour(), false);
you can return right away

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/processor/SkipTurnProcessor.java
>          game.setNextPlayer(game.getPlayers().get(event.getPlayer().getPlayerId()));
this is already done in EndTurnProcessor

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/processor/TakeCardsProcessor.java
> +        event.getPlayer().getCards().addAll(event.getCards());
Do we need to remove these cards from deck?

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +    private Game getLocalGame(String gameId) {
Rename. Local means nothing here.

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +        Mockito.verify(storage).updateGame(game);
you're checking your code above

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +    private GameStorage storage;
remove, you have inMemoryGameStorage

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +    @Mock
must not be a mock, you're testing this class, not  a mock

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/EventServiceImplTest.java
> +        int fromEventId = 0;
Let's put 2-3 events into game and set fromEventId to 1 or 2. Check that not all eevents from game are returned.

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndGameProcessorTest.java
> +        endGameProcessor.doProcess(null, game, null);
Shouldn't you pass event here?

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndTurnProcessorTest.java
> +    void doProcess_changeGameStateAndNextPlayer_startTurn() {
_changeGameStateAndNextPlayer_ must describe a condition. Condition here is that active player still have cards to play, thus game does not end.

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndTurnProcessorTest.java
> +    void doProcess_changeGameStateAndNextPlayer_endGame() {
condition should be _activePlayerHasNoMoreCards_

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/JoinGameProcessorTest.java
> +    void doProcess_joinPlayer() {
you need 2 tests here:
1. test that player just joins
2. test that game start event is spawned, if 2 players are in game

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/PlayCardProcessorTest.java
> +        assertThat(game.getPlayers().get(player.getPlayerId()).getCards()).doesNotContain(card);
you can just use `player.getCards()` instead of `game.getPlayers().get(player.getPlayerId()).getCards()`

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/SkipTurnProcessorTest.java
> +    void doProcess_setCorrectNextPlayer() {
now it shouldn't set next player, only spawn end turn event.

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/StartGameProcessorTest.java
> +        Player secondPlayer = new Player("playerId", null, cardsSecondPlayer);
why both players have same ID?

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/StartTurnProcessorTest.java
> +        Game game = new Game(null, Map.of(player.getPlayerId(), player), null,
Your game has only one player now. You need to test that StartTurnProcessor actually selects next player. So you need 2 players.

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/TurnCardOverProcessorTest.java
> +        assertThat(game.getCardsInTheGame()).contains(event.getCard());
check not that it contains card, but that it ends with that card

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/TurnCardOverProcessorTest.java
> +        assertThat(game.getCardsInTheGame()).contains(event.getCard());
You can also check the size of cards in game. should be 1

2021-03-27 20:45 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(game.getGameId()).isNotNull();
also check that it's not an empty string.

2021-03-28 07:45 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/EventServiceImpl.java
> +    private Card changeCardsParams(Card card) {
renamed it

2021-03-28 07:46 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/EventServiceImpl.java
> +        Card changedCard = new Card(card.getType(), card.getColour(), false);
fixed it

2021-03-28 07:56 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/processor/SkipTurnProcessor.java
>          game.setNextPlayer(game.getPlayers().get(event.getPlayer().getPlayerId()));
deleted it

2021-03-29 07:15 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +    private Game getLocalGame(String gameId) {
renamed it

2021-03-29 08:41 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/processor/TakeCardsProcessor.java
> +        event.getPlayer().getCards().addAll(event.getCards());
I think we must delete this cards from deck, because we moved it to the player

2021-03-29 20:06 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +    private GameStorage storage;
removed

2021-03-29 20:07 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +    @Mock
deleted the annotation

2021-03-29 20:07 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +        Mockito.verify(storage).updateGame(game);
fixed it

2021-03-29 21:58 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/EventServiceImplTest.java
> +        int fromEventId = 0;
changed it

2021-03-29 22:02 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndGameProcessorTest.java
> +        endGameProcessor.doProcess(null, game, null);
we don't need event here, because EndGameProcessor just change GameState

2021-03-29 22:07 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndTurnProcessorTest.java
> +    void doProcess_changeGameStateAndNextPlayer_startTurn() {
renamed it

2021-03-29 22:08 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/EndTurnProcessorTest.java
> +    void doProcess_changeGameStateAndNextPlayer_endGame() {
renamed it

2021-03-29 22:25 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/JoinGameProcessorTest.java
> +    void doProcess_joinPlayer() {
we've already done everything in this one test

2021-03-29 22:30 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/PlayCardProcessorTest.java
> +        assertThat(game.getPlayers().get(player.getPlayerId()).getCards()).doesNotContain(card);
changed it

2021-03-29 22:35 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/SkipTurnProcessorTest.java
> +    void doProcess_setCorrectNextPlayer() {
deleted unnecessary code

2021-03-29 22:37 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/StartGameProcessorTest.java
> +        Player secondPlayer = new Player("playerId", null, cardsSecondPlayer);
changed players id

2021-03-29 23:01 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/StartTurnProcessorTest.java
> +        Game game = new Game(null, Map.of(player.getPlayerId(), player), null,
added second player and test next player

2021-03-29 23:19 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/event/processor/TurnCardOverProcessorTest.java
> +        assertThat(game.getCardsInTheGame()).contains(event.getCard());
done

2021-03-29 23:20 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/event/processor/TakeCardsProcessor.java
> +        event.getPlayer().getCards().addAll(event.getCards());
we need to rework this code

2021-03-29 23:22 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        assertThat(game.getGameId()).isNotNull();
done

2021-03-31 07:34 UTC, merged