create personal exceptions in service
yoursweet667/UNO_Backend pull request #7
Opened 2021-04-03 10:04 UTC by yoursweet667

create exceptions

2021-04-03 10:19 UTC, phreakiboi requested changes

2021-04-03 10:19 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/exception/GameExistException.java
> +    public GameExistException(String message) {
GameAlreadyExists...

2021-04-03 10:19 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/exception/PlayerExistException.java
> +    public PlayerExistException(String message) {
PlayerAlreadyExists

2021-04-03 10:19 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +            throw new PlayerExistException("Player:" + playerName + "already exist");
You add this player to game on line 36. So exception will be always thrown.

2021-04-03 10:19 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +        } else if (!storage.getGame(gameId).get().getPlayers().containsKey(playerId)) {
you call storage.getGame(gameId) 2 times and getGameFromOptional one more time. Instead, assign storage.getGame(gameId)  to a variable at the beginning of the method.

2021-04-03 10:41 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/exception/GameExistException.java
> +    public GameExistException(String message) {
renamed

2021-04-03 10:41 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/exception/PlayerExistException.java
> +    public PlayerExistException(String message) {
renamed

2021-04-03 10:44 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +            throw new PlayerExistException("Player:" + playerName + "already exist");
fixed

2021-04-03 10:45 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +        } else if (!storage.getGame(gameId).get().getPlayers().containsKey(playerId)) {
done

2021-04-05 10:17 UTC, phreakiboi requested changes

2021-04-05 10:17 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +        if (getGameFromOptional(gameId).getPlayers().containsValue(player)) {
`getGameFromOptional(gameId).getPlayers()` вызываешь на 38й и 41 строке, но ты можешь делать это один раз и назначить в переменную

2021-04-05 10:17 UTC, phreakiboi commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
>          getGameFromOptional(gameId).getPlayers().remove(playerId);
`getGameFromOptional(gameId).getPlayers()` можно вынести в переменную в этом методе

2021-04-05 10:17 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +        inMemoryGameStorage.createGame(game);
это должно быть в when?

2021-04-05 10:17 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
>          inMemoryGameStorage.updateGame(game);
в чем смысл делать update, если ты только что передал ту же самую игру в `createGame`?

2021-04-05 10:17 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
>          assertThat(returnedGame.isPresent());
что делает эта строка?

2021-04-05 10:17 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +        inMemoryGameStorage.createGame(game);
если ты не тестируешь `createGame` в этом методе, то его вызов не должен быть в when.

2021-04-05 10:17 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        players.put(player.getPlayerId(), player);
не обязатеольно создавать игрока, т.к. в самом тесте ты ничего с ним не делаешь и результат от него не зависит.

2021-04-05 10:17 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        Game game = new Game(GAME_ID, players, null,
зачем ты создаешь игру и игрока?

2021-04-05 11:05 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
> +        if (getGameFromOptional(gameId).getPlayers().containsValue(player)) {
создал отдельную переменную и применил ее

2021-04-05 11:07 UTC, yoursweet667 commented on UNO/src/main/java/ru/yoursweet667/uno/service/game/GameServiceImpl.java
>          getGameFromOptional(gameId).getPlayers().remove(playerId);
это уже было сделано, забыл внести изменение в else

2021-04-05 11:08 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +        inMemoryGameStorage.createGame(game);
перенес в Given, так как это условие теста

2021-04-05 11:13 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
>          inMemoryGameStorage.updateGame(game);
мы проверяем работу метода updateGame, если удалить createGame - тест будет падать с ошибкой (Game with id: gameId doesn't exist), нам необходимо сначала создавать игру, чтобы в последующем изменять ее

2021-04-05 11:15 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
>          assertThat(returnedGame.isPresent());
исправил

2021-04-05 11:17 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        players.put(player.getPlayerId(), player);
учел замечание

2021-04-05 11:17 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
> +        inMemoryGameStorage.createGame(game);
исправил

2021-04-05 11:22 UTC, yoursweet667 commented on UNO/src/test/java/ru/yoursweet667/uno/service/game/GameServiceImplTest.java
> +        Game game = new Game(GAME_ID, players, null,
когда писал тесты копипастил много кода, забыл почистить

2021-04-05 14:46 UTC, phreakiboi approved these changes

2021-04-05 14:46 UTC, phreakiboi commented on UNO/src/test/java/ru/yoursweet667/uno/dataaccess/game/InMemoryGameStorageTest.java
>          inMemoryGameStorage.updateGame(game);
но у тебя игра та же самая. как ты убедишься, что что-то в storage изменилось?
если метод `updateGame` ничего не будет делать (или если ты его даже не будешь вызывать), то тест пройдет.
проверяй, что игра действительно меняется.

2021-05-25 07:56 UTC, merged