Create API doc for application
yoursweet667/UNO_Backend pull request #9
Opened 2021-05-16 21:02 UTC by yoursweet667

2021-05-17 08:15 UTC, phreakiboi requested changes

2021-05-17 08:15 UTC, phreakiboi commented on UNO/OpenAPI/openapi.yaml
> +          "gameId": "gameId",
В api для создания команды уже есть gameId в пути, так что тут он ни к чему

2021-05-17 08:15 UTC, phreakiboi commented on UNO/OpenAPI/openapi.yaml
> +        {
еще, кст, нужно указать тип команды - иначе сервер не поймет чего ты хочешь)

2021-05-17 08:50 UTC, yoursweet667 commented on UNO/OpenAPI/openapi.yaml
> +        {
исправил этот момент

2021-05-17 09:04 UTC, yoursweet667 commented on UNO/OpenAPI/openapi.yaml
> +          "gameId": "gameId",
исправил

2021-05-17 14:08 UTC, phreakiboi approved these changes

2021-06-01 11:16 UTC, phreakiboi approved these changes

2021-06-04 15:34 UTC, merged